resources:
  - name: version
    type: semver
    source:
      initial_version: 0.1.0
      driver: git
      branch: version
      file: number
      uri: {{git-url}}
      private_key: {{private-repo-key}}

  - name: source-code
    type: git
    source:
      branch: master
      uri: {{git-url}}
      private_key: {{private-repo-key}}

  - name: cf-dev
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: development
      skip_cert_check: false
#
#- name: production-code
#  type: git
#  source:
#    branch: master
#    uri: {{git-url}}
#    private_key: {{private-repo-key}}
#    tag_filter: /*-beta\.*/

jobs:
  - name: backend-tests
    plan:
      - get: source-code
        trigger: true
      - task: backend-tests
        file: source-code/concourse/backend/tests/task.yml

  - name: frontend-tests
    plan:
      - get: source-code
        trigger: true
      - task: frontend-tests
        file: source-code/concourse/frontend/tests/task.yml

  - name: bump-version
    plan:
      - get: source-code
        trigger: true
        passed: [backend-tests, frontend-tests]
      - get: version
        params: { bump: minor, pre: beta }
      - put: version
        params: { file: version/number }

  - name: deploy-backend-dev
    plan:
      - get: source-code
        trigger: true
        passed: [bump-version]
      - get: version
        passed: [bump-version]
      - task: build-backend-dev
        file: source-code/concourse/backend/build-dev/task.yml
      - put: cf-dev
        params:
          manifest: build-output/manifests/development/backend.yml

  - name: deploy-frontend-dev
    plan:
      - get: source-code
        trigger: true
        passed: [bump-version]
      - get: version
        passed: [bump-version]
      - task: build-frontend-dev
        file: source-code/concourse/frontend/build-dev/task.yml
      - put: cf-dev
        params:
          manifest: build-output/manifests/development/frontend.yml

  - name: tag-prerelease
    plan:
      - get: source-code
        trigger: true
        passed: [deploy-frontend-dev, deploy-backend-dev]
      - get: version
        passed: [deploy-frontend-dev, deploy-backend-dev]
      - put: source-code
        params:
          repository: source-code
          tag: version/number
          only_tag: true

#  - name: deploy-prod
#    plan:
#      - get: version
#      - get: production-code
#      - task: deploy-prod
#        file: production-code/deploy-prod/task.yml
#
#  - name: tag-release
#    plan:
#      - get: version
#        trigger: true
#        passed: [deploy-prod]
#        params: { bump: final }
#      - get: production-code
#        passed: [deploy-prod]
#      - put: production-code
#        params:
#          repository: production-code
#          tag: version/number
#          only_tag: true
#      - put: version
#        params: { file: version/number }
